Adafruit IO: AIO-0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
Adobe Device Token: 01234567-89ab-cdef-0123-456789abcdef
Amazon AWS Access Key ID: AKIA1234567890EXAMPLE
Amazon AWS Secret Access Key: abcdefghijklmnopqrstuvwxyz1234567890+/=
Atlassian API Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Azure Active Directory Application Secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Azure CosmosDB Key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Azure DevOps Personal Access Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DigitalOcean Personal Access Token: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef
Discord Bot Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Dropbox Access Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Dynatrace Access Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Figma Personal Access Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
GitHub Personal Access Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Google API Key: AIzaSyD-xEHt5_fiZGwhw_lAKvNgE-wmWjKzzX0
Mailchimp API Key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-us1
NuGet API Key: abcdefghijklmnopqrstuvwxyz1234567890
OpenAI API Key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Pulumi Access Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Stripe API Key: sk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Twilio API Key: ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Typeform Personal Access Token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Yandex.Cloud IAM Token: yyy.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx